[package]
name = "fm"
version = "0.1.0"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2018"
description = "tiny file manager with vim-like keybind"
repository = "https://github.com/kyoheiu/fm"
license = "MIT"
[dependencies]
chrono = "*"
dirs = "4.0.0"
fs_extra = "1.2.0"
termion = "1.5.6"
toml = "0.5.8"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
