[package]
name = "felix"
version = "0.9.6"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2021"
description = "tui file manager with vim-like key mapping"
readme = "README_crates.md"
repository = "https://github.com/kyoheiu/felix"
license = "MIT"
keywords = ["tui", "termion", "file-manager"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "fx"
path = "src/main.rs"
test = true
bench = false

[profile.release]
strip = true

[dependencies]
termion = "1.5.6"
dirs = "4.0.0"
walkdir = "2.3.2"
natord = "1.0.9"
thiserror = "1.0.30"
chrono = "0.4.19"
toml = "0.5.8"
log = "0.4.16"
simplelog = "0.12.0"
image = "0.24.2"
viuer = "0.6.1"
console = "0.15.0"
tempfile = "3.3.0"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]
