[package]
name = "fm"
version = "0.2.2"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2018"
description = "simple TUI file manager with vim-like keybind"
license = "MIT"
repository = "https://github.com/kyoheiu/fm"
keywords = ["tui", "termion", "file-manager"]
categories = ["command-line-utilities", "filesystem"]
readme = "README.md"

[dependencies]
chrono = "*"
clipboard = "*"
dirs = "4.0.0"
natord = "*"
termion = "1.5.6"
toml = "0.5.8"
walkdir = "*"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
