[package]
name = "felix"
version = "0.2.12"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2018"
description = "tui file manager with vim-like key mapping"
readme = "README_crates.md"
repository = "https://github.com/kyoheiu/felix"
license = "MIT"
keywords = ["tui", "termion", "file-manager"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "fx"
path = "src/main.rs"
test = false
bench = false

[dependencies]
chrono = "0.4.19"
# clipboard = "0.5.0"
dirs = "4.0.0"
natord = "1.0.9"
termion = "1.5.6"
toml = "0.5.8"
walkdir = "2.3.2"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
