[package]
name = "felix"
version = "0.9.1"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2021"
description = "tui file manager with vim-like key mapping"
readme = "README_crates.md"
repository = "https://github.com/kyoheiu/felix"
license = "MIT"
keywords = ["tui", "termion", "file-manager"]
categories = ["command-line-utilities", "filesystem"]

[[bin]]
name = "fx"
path = "src/main.rs"
test = true
bench = false

[profile.release]
strip = true

[dependencies]
chrono = "0.4.19"
dirs = "4.0.0"
natord = "1.0.9"
termion = "1.5.6"
toml = "0.5.8"
walkdir = "2.3.2"
log = "0.4.16"
env_logger = "0.9.0"
thiserror = "1.0.30"
viuer = "0.6.1"
image = "0.24.2"

[dependencies.serde]
version = "1.0.136"
features = ["derive"]
