[package]
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
categories = ["command-line-utilities", "filesystem"]
description = "simple TUI file manager with vim-like keybind"
edition = "2018"
keywords = ["tui", "termion", "file-manager"]
license = "MIT"
name = "fx-rs"
readme = "README.md"
repository = "https://github.com/kyoheiu/fx"
version = "0.2.3"

[[bin]]
name = "fx"
path = "src/main.rs"
test = false
bench = false

[dependencies]
chrono = "*"
clipboard = "*"
dirs = "4.0.0"
natord = "*"
termion = "1.5.6"
toml = "0.5.8"
walkdir = "*"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
