[package]
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
description = "simple TUI file manager with vim-like keybind"
edition = "2018"
license = "MIT"
name = "fm"
repository = "https://github.com/kyoheiu/fm"
version = "0.1.1"
[dependencies]
chrono = "*"
dirs = "4.0.0"
natord = "*"
termion = "1.5.6"
toml = "0.5.8"
walkdir = "*"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
