[package]
name = "ncu"
version = "0.1.0"
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pancurses = "0.16"
