[package]
authors = ["Kyohei Uto <kyoheiu@outlook.com>"]
edition = "2018"
name = "fm"
version = "0.1.0"
[dependencies]
chrono = "*"
dirs = "4.0.0"
fs_extra = "1.2.0"
termion = "1.5.6"
toml = "0.5.8"

[dependencies.serde]
features = ["derive"]
version = "1.0.130"
