# 1.3.2

# (Optional)
# key (the command you want to use) = [values] (extensions)
# [exec]
# feh = [\"jpg\", \"jpeg\", \"png\", \"gif\", \"svg\"]
# zathura = [\"pdf\"]

# (Optional) Whether to use syntax highlighting in the preview mode.
# If not set, will default to false.
# syntax_highlight = false

# (Optional) Path to .tmtheme file for the syntax highlighting.
# If not set, felix uses `base16-mocha.dark`.
# theme_path = \"\"

# The foreground color of directory, file and symlink.
# Pick one of the following:
#     Black
#     Red
#     Green
#     Yellow
#     Blue
#     Magenta
#     Cyan
#     White
#     LightBlack
#     LightRed
#     LightGreen
#     LightYellow
#     LightBlue
#     LightMagenta
#     LightCyan
#     LightWhite
#     Rgb(u8, u8, u8)
#     AnsiValue(u8)
[color]
dir_fg = "LightCyan"
file_fg = "LightWhite"
symlink_fg = "LightYellow"
