# Choose the foreground color of file and directory in the list.
# Pick one of the following:
#   AnsiValue
#   Black
#   Blue
#   Cyan
#   Green
#   LightBlack
#   LightBlue
#   LightCyan
#   LightGreen
#   LightMagenta
#   LightRed
#   LightWhite
#   LightYellow
#   Magenta
#   Red
#   Rgb(u8, u8, u8)
#   White
#   Yellow
[color]
dir_fg = "LightGreen"
file_fg = "LightWhite"

# key(extention) = value(shell command you want to use)
# key `default` is mandatory (if it does not exist, program will panic.)
[exec]
default = "nvim"
jpg = "feh"
pdf = "zathura"
png = "feh"
