version: 2.1

jobs:
  build:
    shell: /bin/bash
    docker:
      - image: circleci/rust
    steps:
      - checkout
      - run:
          command: |
            echo running build test
            sudo apt update
            sudo apt-get install libxcb-composite0-dev
            cargo install --path .

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build-test:
    jobs:
      - build
