name: 'install test'

on:
  push:
    branches: [ ghactions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: rust-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: cargo install --path .
